### ISSUE TITLE
Failed startup of context o.e.j.w.WebAppContext@624ea235{Bigdata,/blazegraph,file:///var/lib/jetty/webapps/blazegraph/,UNAVAILABLE}{/var/lib/jetty/webapps/blazegraph}

### ISSUE THREAD

**Issue by olea** [researchspace/researchspace-docker-compose#2]
Context:

- downloaded repo
- cd full-setup/
- configured .env
- executed ./fix-folder-permissions.sh
- executed docker-compose up

Then get this:

```

blazegraph_1        | 2024-02-14 16:41:04.873:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@624ea235{Bigdata,/blazegraph,file:///var/lib/jetty/webapps/blazegraph/,UNAVAILABLE}{/var/lib/jetty/webapps/blazegraph}
blazegraph_1        | java.lang.RuntimeException: java.lang.RuntimeException: file=/blazegraph-data/blazegraph.jnl
blazegraph_1        | 	at com.bigdata.rdf.sail.webapp.BigdataRDFServletContextListener.openIndexManager(BigdataRDFServletContextListener.java:805)
blazegraph_1        | 	at com.bigdata.rdf.sail.webapp.BigdataRDFServletContextListener.contextInitialized(BigdataRDFServletContextListener.java:277)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:933)
blazegraph_1        | 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:892)
blazegraph_1        | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:356)
blazegraph_1        | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
blazegraph_1        | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:825)
blazegraph_1        | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
blazegraph_1        | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
blazegraph_1        | 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:513)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:154)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:173)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:427)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:784)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:753)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:540)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:146)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:599)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:249)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
blazegraph_1        | 	at org.eclipse.jetty.server.Server.start(Server.java:407)
blazegraph_1        | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
blazegraph_1        | 	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$1(XmlConfiguration.java:1924)
blazegraph_1        | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
blazegraph_1        | 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1873)
blazegraph_1        | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
blazegraph_1        | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
blazegraph_1        | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
blazegraph_1        | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
blazegraph_1        | 	at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
blazegraph_1        | 	at org.eclipse.jetty.start.Main.start(Main.java:491)
blazegraph_1        | 	at org.eclipse.jetty.start.Main.main(Main.java:77)
blazegraph_1        | Caused by: 
blazegraph_1        | java.lang.RuntimeException: file=/blazegraph-data/blazegraph.jnl
blazegraph_1        | 	at com.bigdata.journal.FileMetadata.<init>(FileMetadata.java:851)
blazegraph_1        | 	at com.bigdata.journal.FileMetadata.createInstance(FileMetadata.java:1513)
blazegraph_1        | 	at com.bigdata.journal.AbstractJournal.<init>(AbstractJournal.java:1156)
blazegraph_1        | 	at com.bigdata.journal.Journal.<init>(Journal.java:276)
blazegraph_1        | 	at com.bigdata.journal.Journal.<init>(Journal.java:269)
blazegraph_1        | 	at com.bigdata.rdf.sail.webapp.BigdataRDFServletContextListener.openIndexManager(BigdataRDFServletContextListener.java:799)
blazegraph_1        | 	at com.bigdata.rdf.sail.webapp.BigdataRDFServletContextListener.contextInitialized(BigdataRDFServletContextListener.java:277)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:933)
blazegraph_1        | 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:892)
blazegraph_1        | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:356)
blazegraph_1        | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
blazegraph_1        | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:825)
blazegraph_1        | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
blazegraph_1        | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
blazegraph_1        | 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:513)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:154)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:173)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:427)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:784)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:753)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:540)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:146)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:599)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:249)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
blazegraph_1        | 	at org.eclipse.jetty.server.Server.start(Server.java:407)
blazegraph_1        | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
blazegraph_1        | 	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$1(XmlConfiguration.java:1924)
blazegraph_1        | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
blazegraph_1        | 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1873)
blazegraph_1        | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
blazegraph_1        | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
blazegraph_1        | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
blazegraph_1        | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
blazegraph_1        | 	at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
blazegraph_1        | 	at org.eclipse.jetty.start.Main.start(Main.java:491)
blazegraph_1        | 	at org.eclipse.jetty.start.Main.main(Main.java:77)
blazegraph_1        | Caused by: 
blazegraph_1        | java.io.FileNotFoundException: /blazegraph-data/blazegraph.jnl (Permission denied)
blazegraph_1        | 	at java.base/java.io.RandomAccessFile.open0(Native Method)
blazegraph_1        | 	at java.base/java.io.RandomAccessFile.open(Unknown Source)
blazegraph_1        | 	at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
blazegraph_1        | 	at java.base/java.io.RandomAccessFile.<init>(Unknown Source)
blazegraph_1        | 	at com.bigdata.journal.FileMetadata.reopenChannel(FileMetadata.java:1195)
blazegraph_1        | 	at com.bigdata.journal.FileMetadata.access$000(FileMetadata.java:58)
blazegraph_1        | 	at com.bigdata.journal.FileMetadata$1.reopenChannel(FileMetadata.java:1163)
blazegraph_1        | 	at com.bigdata.journal.FileMetadata$1.reopenChannel(FileMetadata.java:1153)
blazegraph_1        | 	at com.bigdata.journal.FileMetadata.<init>(FileMetadata.java:464)
blazegraph_1        | 	at com.bigdata.journal.FileMetadata.createInstance(FileMetadata.java:1513)
blazegraph_1        | 	at com.bigdata.journal.AbstractJournal.<init>(AbstractJournal.java:1156)
blazegraph_1        | 	at com.bigdata.journal.Journal.<init>(Journal.java:276)
blazegraph_1        | 	at com.bigdata.journal.Journal.<init>(Journal.java:269)
blazegraph_1        | 	at com.bigdata.rdf.sail.webapp.BigdataRDFServletContextListener.openIndexManager(BigdataRDFServletContextListener.java:799)
blazegraph_1        | 	at com.bigdata.rdf.sail.webapp.BigdataRDFServletContextListener.contextInitialized(BigdataRDFServletContextListener.java:277)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:933)
blazegraph_1        | 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:892)
blazegraph_1        | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:356)
blazegraph_1        | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
blazegraph_1        | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:825)
blazegraph_1        | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
blazegraph_1        | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:46)
blazegraph_1        | 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:513)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:154)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:173)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:427)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:66)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:784)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:753)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:641)
blazegraph_1        | 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:540)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:146)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:599)
blazegraph_1        | 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:249)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
blazegraph_1        | 	at org.eclipse.jetty.server.Server.start(Server.java:407)
blazegraph_1        | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
blazegraph_1        | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
blazegraph_1        | 	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
blazegraph_1        | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
blazegraph_1        | 	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$1(XmlConfiguration.java:1924)
blazegraph_1        | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
blazegraph_1        | 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1873)
blazegraph_1        | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
blazegraph_1        | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
blazegraph_1        | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
blazegraph_1        | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
blazegraph_1        | 	at org.eclipse.jetty.start.Main.invokeMain(Main.java:218)
blazegraph_1        | 	at org.eclipse.jetty.start.Main.start(Main.java:491)
blazegraph_1        | 	at org.eclipse.jetty.start.Main.main(Main.java:77)
blazegraph_1        | 2024-02-14 16:41:04.914:INFO:oejs.AbstractConnector:main: Started ServerConnector@4f8caaf3{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
blazegraph_1        | 2024-02-14 16:41:04.917:INFO:oejs.Server:main: Started @5533ms
```

Is there something I could fix by myself?

Thanks.

**Comment by JuanjoSalvador** [comment]
Problem here seems to be `blazegraph` container not being setup properly, since even with proper permissions, `blazegraph.jnl` cannot be created. With access to Blazegraph Dockerfile we can check and fix this, at least a workaround.

Considering running a separated non-docker instance of Blazegraph since there is no trusted and vanilla images on DockerHub, or building your own.

**Comment by olea** [comment]
> * executed ./fix-folder-permissions.sh

Seems the problem is this should be executed with root credentials:

```
sudo sh  ./fix-folder-permissions.sh
```

This way the container looks to be running by the application is still taking ages to set up.
